import "./js/header/toggleAsideNav.js";
import "./js/header/toggleElementsForAside.js";
import "./js/header/toggleMode.js";
import "./js/main/scroll/byWheel.js";
import "./js/main/scroll/byAnchors.js";
import "./js/main/project-detail/openProjectDetail.js";
import "./js/main/project-detail/closeProjectDetail.js";
import "./js/main/intersection-observer/sectionsContent.js";
import "./js/main/intersection-observer/activeAnchor.js";
